### ISSUE TITLE
Uncaught Exception: Command Failed

### ISSUE THREAD

**Issue by cdokolas** [henryboldi/felony#14]
I get the following when I launch `Felony-0.10.2-win.exe` on my Windows 10 machine.

Notes:
- Initially, the splash graphic/animation comes on and a small Electron window right behind it.
- After a few seconds, the dialog shown in the screenshot appears.
- The dialog closes by itself after a few seconds and is repeated a second time (the second time it stays until I press Ok).
- The Electron window (I assume it is the basic Electron UI before the app loads) stays on screen, but I can't do much with the menus.
- After a while, I see the same error dialog again (several minutes must pass).

![felony_1](https://cloud.githubusercontent.com/assets/1136790/16561690/2f83faca-4203-11e6-9a3c-e4d980638fa3.png)

**Comment by globz** [comment]
I confirm the same error on Windows, just tried the same build 10 minutes ago.

**Comment by henryboldi** [comment]
Whoops... Would super appreciate a PR on this issue!

**Comment by cougarten** [comment]
same here. Text of the error for easy reading:

`[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: Command failed: 4294967295
System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__50`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.FileDownloader.<DownloadUrl>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__3f.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<Download>d__5d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)
---> (Inner Exception #0) System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__50`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.FileDownloader.<DownloadUrl>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__3f.Mov`

**Comment by AyrA** [comment]
Also happens with Version `0.10.3`

**Comment by nopesled** [comment]
I've had this error occur on windows 7 also

**Comment by pherelad** [comment]
I'm having this problem as well on Windows 7.

**Comment by IwishIcanFLighT** [comment]
```
System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
```
Seems like the installer is crashing because a remote server fails on him (Error 500). Any idea what the installer is fetching during install?

**Comment by frankcash** [comment]
I have this problem on osx sometimes. I'll launch the app and the local
host web server will not be running yet.

**Comment by michaelpittino** [comment]
Any fix for this problem?

**Comment by maiph** [comment]
any updates on this? or another way of getting it working?

**Comment by frankcash** [comment]
Hey Maiph, I don't have access to Windows but if you'd love to hop on
hangouts or Skype sometime I'd help debug this. I would also accept a PR
(and love to do such)

**Comment by maiph** [comment]
I can help on hangout. Just send a message there.

On sáb, ago 27, 2016 at 3:33 PM, Frank Cash <notifications@github.com> wrote:
Hey Maiph, I don't have access to Windows but if you'd love to hop on
hangouts or Skype sometime I'd help debug this. I would also accept a PR
(and love to do such)

**Comment by frankcash** [comment]
Sounds good, could we schedule something for sometime during the week like
Wednesday or Thursday?

**Comment by maiph** [comment]
Wednesday sounds good

On sáb, ago 27, 2016 at 3:39 PM, Frank Cash <notifications@github.com> wrote:
Sounds good, could we schedule something for sometime during the week like
Wednesday or Thursday?

**Comment by Maxime10** [comment]
Same error here... Any update planned to fix this ? Thanks

**Comment by frankcash** [comment]
Hmm, I don't have a windows machine and I missed a chance to hangout with someone who does.  If another contributor that has windows will fix this that'd be great.  I'd also love to merge in a contribution for this.
