### ISSUE TITLE
OS X: When window is closed, Toggle Full Screen causes error

### ISSUE THREAD

**Issue by danielhoherd** [henryboldi/felony#46]
```
A JavaScript error occurred in the main process

Uncaught Exception:
TypeError: Cannot read property 'setFullScreen' of null
    at darwin.process.platform.u.submenu.click (/Users/hoherd/Downloads/Felony.app/Contents/Resources/app/webpack:/main.development.js:169:11)
    at MenuItem.click (/Users/hoherd/Downloads/Felony.app/Contents/Resources/electron.asar/browser/api/menu-item.js:81:16)
    at Function.delegate.executeCommand (/Users/hoherd/Downloads/Felony.app/Contents/Resources/electron.asar/browser/api/menu.js:119:40)
```

**Comment by henryboldi** [comment]
Thanks for the bug report! I would love to see a PR resolving this.

**Comment by tobycyanide** [comment]
I've got a fix for this, waiting for my other PR to get merged, it's just:
```js
if (!!mainWindow) {
    mainWindow.setFullScreen(!mainWindow.isFullScreen())
}
````

**Comment by frankcash** [comment]
This issue seems to no longer persist thanks to @tobycyanide  (https://github.com/henryboldi/felony/pull/62)
