### ISSUE TITLE
Unable to run on Mac

### ISSUE THREAD

**Issue by tobycyanide-pwr** [henryboldi/felony#52]
I have set the developer ID to '-', but I get an error running `npm run dev`, it errors on
` cross-env HOT=1 NODE_ENV=development electron -r babel-register ./main.development`
I believe this is an error with how electrum/node are spawning new processes.  The stacktrace is:
```js 
 Error: spawn electron ENOENT
     at exports._errnoException (util.js:1007:11)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
     at onErrorNT (internal/child_process.js:348:16)
     at _combinedTickCallback (internal/process/next_tick.js:74:11)
     at process._tickCallback (internal/process/next_tick.js:98:9)
     at Module.runMain (module.js:577:11)
     at run (node.js:348:7)
     at startup (node.js:140:9)
     at node.js:463:3
```
I'd love to be able to contribute to this project, and definitely will, but this error is a bit of a show-stopper.
Thanks!

**Comment by achekroud** [comment]
same error here -- along with an electron window popping up that says: 

``` 
Uncaught Exception:
TypeError: Cannot read property 'on' of undefined
    at Object.<anonymous> (/Users/adamchekroud/felony/node_modules/electron-localshortcut/index.js:118:4)
    at Module._compile (module.js:413:34)
    at Module._extensions..js (module.js:422:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/adamchekroud/felony/node_modules/babel-register/lib/node.js:166:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/adamchekroud/felony/node_modules/electron-debug/index.js:3:23)
    at Module._compile (module.js:413:34)
```

**Comment by wdiechmann** [comment]
I see somewhat that too - this is how far I got:

```
Error: node 6.2.2 already installed
$ npm install -g concurrently
(node:31178) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
/Users/walther/.node/bin/concurrently -> /Users/walther/.node/lib/node_modules/concurrently/src/main.js
/Users/walther/.node/bin/concurrent -> /Users/walther/.node/lib/node_modules/concurrently/src/main.js
/Users/walther/.node/lib
└─┬ concurrently@2.2.0 
  ├── bluebird@2.9.6 
  ├─┬ chalk@0.5.1 
  │ ├── ansi-styles@1.1.0 
  │ ├── escape-string-regexp@1.0.5 
  │ ├─┬ has-ansi@0.1.0 
  │ │ └── ansi-regex@0.2.1 
  │ ├── strip-ansi@0.3.0 
  │ └── supports-color@0.2.0 
  ├── commander@2.6.0 
  ├─┬ cross-spawn@0.2.9 
  │ └── lru-cache@2.7.3 
  ├── lodash@4.13.1 
  ├── moment@2.14.1 
  └── rx@2.3.24 

$ npm run dev

> felony@0.10.3 dev /Users/walther/Projects/Electron/felony
> concurrently --kill-others "npm run hot-server" "npm run start-hot"

[1] 
[1] > felony@0.10.3 start-hot /Users/walther/Projects/Electron/felony
[1] > cross-env HOT=1 NODE_ENV=development electron -r babel-register ./main.development
[1] 
[0] 
[0] > felony@0.10.3 hot-server /Users/walther/Projects/Electron/felony
[0] > node -r babel-register server.js
[0] 
[1] sh: cross-env: command not found
[1] 
[1] npm
[1]  
[1] ERR!
[1]  Darwin 15.5.0
[1] npm
[1]  ERR! argv "/usr/local/Cellar/node/6.2.2/bin/node" "/usr/local/bin/npm" "run" "start-hot"
[1] npm ERR!
[1]  node v6.2.2
[1] npm
[1]  ERR! npm  v2.14.12
[1] npm
[1]  
[1] ERR! file sh
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! errno ENOENT
[1] npm ERR! syscall spawn
[1] npm ERR! felony@0.10.3 start-hot: `cross-env HOT=1 NODE_ENV=development electron -r babel-register ./main.development`
[1] npm ERR! spawn ENOENT
[1] npm ERR!
[1]  
[1] npm ERR! Failed at the felony@0.10.3 start-hot script 'cross-env HOT=1 NODE_ENV=development electron -r babel-register ./main.development'.
[1] npm ERR! This is most likely a problem with the felony package,
[1] npm ERR! not with npm itself.
[1] npm ERR! Tell the author that this fails on your system:
[1] npm ERR!     cross-env HOT=1 NODE_ENV=development electron -r babel-register ./main.development
[1] npm ERR! You can get their info via:
[1] npm ERR!     npm owner ls felony
[1] npm ERR! There is likely additional logging output above.
[1] 
[1] npm ERR! Please include the following file with any support request:
[1] npm ERR!     /Users/walther/Projects/Electron/felony/npm-debug.log
[1] npm run start-hot exited with code 1
[0] module.js:442
[0]     throw err;
[0]     ^
[0] 
[0] Error: Cannot find module 'babel-register'
[0]     at Function.Module._resolveFilename (module.js:440:15)
[0]     at Function.Module._load (module.js:388:25)
[0]     at Module.require (module.js:468:17)
[0]     at module.js:632:12
[0]     at Array.forEach (native)
[0]     at Function.Module._preloadModules (module.js:631:12)
[0]     at preloadModules (node.js:319:38)
[0]     at startup (node.js:139:9)
[0]     at node.js:463:3
[0] 
[0] npm
[0]  ERR!
[0]  Darwin 15.5.0
[0] npm ERR! argv
[0]  "/usr/local/Cellar/node/6.2.2/bin/node" "/usr/local/bin/npm" "run" "hot-server"
[0] npm ERR! node v6.2.2
[0] npm ERR!
[0]  npm  v2.14.12
[0] npm ERR! code ELIFECYCLE
[0] npm ERR!
[0]  felony@0.10.3 hot-server: `node -r babel-register server.js`
[0] npm ERR! Exit status 1
[0] npm 
[0] ERR! 
[0] npm ERR! Failed at the felony@0.10.3 hot-server script 'node -r babel-register server.js'.
[0] npm 
[0] ERR! This is most likely a problem with the felony package,
[0] npm ERR! not with npm itself.
[0] npm ERR!
[0]  Tell the author that this fails on your system:
[0] npm ERR!     node -r babel-register server.js
[0] npm ERR!
[0]  You can get their info via:
[0] npm ERR!
[0]      npm owner ls felony
[0] npm ERR! There is likely additional logging output above.
[0] 
[0] npm ERR! Please include the following file with any support request:
[0] npm ERR!
[0]      /Users/walther/Projects/Electron/felony/npm-debug.log
[0] npm run hot-server exited with code 1

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/6.2.2/bin/node" "/Users/walther/.node/bin/npm" "run" "dev"
npm ERR! node v6.2.2
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! felony@0.10.3 dev: `concurrently --kill-others "npm run hot-server" "npm run start-hot"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the felony@0.10.3 dev script 'concurrently --kill-others "npm run hot-server" "npm run start-hot"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the felony package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     concurrently --kill-others "npm run hot-server" "npm run start-hot"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs felony
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls felony
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/walther/Projects/Electron/felony/npm-debug.log
$ 
```

**Comment by henryboldi** [comment]
Looking into this. Thanks everyone!

**Comment by chovy** [comment]
I just get a blank screen:

![screenshot 2016-07-11 00 10 10](https://cloud.githubusercontent.com/assets/27381/16722501/e705f9da-46fb-11e6-9f91-a69a033b4eb9.png)

**Comment by tobycyanide-pwr** [comment]
Got it to open, but now just getting a blank screen.  I ran a bunch of npm commands, and pulled from master, but that's all I remember

**Comment by tobycyanide-pwr** [comment]
Running sudo npm rebuild got it to work... Apparently there was a version mismatch from a package on my system being built for an older version of node.  Program opens now and appears to work.
